import React, { useState, useRef, useEffect } from 'react';
import { Shield, LayoutGrid, List, ExternalLink, X } from 'lucide-react';
import { Helmet } from "react-helmet-async";

export default function HowToEnable({
  cardWidth = 600,
  cardHeight = 'auto',
  cardBg = 'bg-white/95',
  cardBlur = 'backdrop-blur-md',
  cardShadow = 'shadow-xl',
  cardBorder = 'border border-slate-200',
  dragByHeaderOnly = true, // drag only by header
}) {
  const [view, setView] = useState("grid");
  const [selectedPlatform, setSelectedPlatform] = useState(null);
  const [dragging, setDragging] = useState(false);
  const [position, setPosition] = useState({ x: 0, y: 100 });
  const dragRef = useRef(null);
  const offsetRef = useRef({ x: 0, y: 0 });

  const platforms = [
    {
      name: 'Google', path: 'Security > 2-Step Verification', description: 'Email, Cloud Storage & Productivity', icon: 'https://www.google.com/favicon.ico', instructions: [
        "Go to your Google Account by clicking your profile picture and selecting 'Manage your Google Account'.",
        "Select the 'Security' tab from the left-hand menu.",
        "Under 'Signing in to Google', click on '2-Step Verification' and then 'Get Started'.",
        "Follow the on-screen prompts.",
        "When asked to choose a verification method, select 'Authenticator app'.",
        "Scan the QR code using the 2Fa Live app to complete setup."
      ]
    },
    {
      name: 'Facebook', path: 'Settings > Password & Security', description: 'Social Networking Platform', icon: 'https://www.facebook.com/favicon.ico', instructions: [
        "Click the down-arrow in the top-right corner.",
        "Go to 'Settings & Privacy' > 'Settings'.",
        "Click on 'Security and Login'.",
        "Scroll to 'Use two-factor authentication' and click 'Edit'.",
        "Select 'Authentication App' as your method.",
        "Scan the QR code with the 2Fa Live app to finalize setup."
      ]
    },
    {
      name: 'Instagram', path: 'Settings > Security > 2FA', description: 'Social Networking Platform', icon: 'https://www.instagram.com/static/images/ico/favicon.ico/36b304827392.ico', instructions: [
        "Go to your profile and tap the menu icon (three horizontal lines) in the top-right corner.",
        "Tap 'Settings' > 'Security' > 'Two-Factor Authentication'.",
        "Tap 'Get Started'. Choose 'Authentication App' as your method.",
        "Follow the on-screen instructions. Instagram will show you a QR code.",
        "Scan the QR code with the 2Fa Live app to link your account."
      ]
    },
    {
      name: 'X (Social Platform)', path: 'Settings > Security > 2FA', description: 'Visual Sharing & Social Media', icon: 'https://abs.twimg.com/favicons/twitter.ico', instructions: [
        "Log into your account.",
        "Navigate to your Security or Privacy settings.",
        "Find 'Two-Factor Authentication' or '2-Step Verification'.",
        "Choose 'Authenticator App' as your method.",
        "Scan the QR code using the 2Fa Live app.",
        "Enter the 6-digit code to confirm and save recovery codes."
      ]
    },
    {
      name: 'GitHub', path: 'Settings > Password & Security', description: 'Microblogging & News Updates', icon: 'https://github.com/favicon.ico', instructions: [
        "In the upper-right corner of any page, click your profile photo, then click 'Settings'.",
        "In the 'Access' section of the sidebar, click 'Password and authentication'.",
        "In the 'Two-factor authentication' section, click 'Enable two-factor authentication'.",
        "Under 'Scan the QR code', use the 2Fa Live app to scan the code.",
        "Enter the code generated by the app to complete the setup."
      ]
    },
    {
      name: 'Amazon', path: 'Login & Security > 2SV', description: 'Code Collaboration & Version Control', icon: 'https://www.amazon.com/favicon.ico', instructions: [
        "Go to 'Your Account' > 'Login & Security'.",
        "Click 'Edit' next to 'Two-Step Verification (2SV) Settings'.",
        "Click 'Get Started'. Choose 'Authenticator App' as your method.",
        "The site will display a QR code. Use the 2Fa Live app to scan it.",
        "Enter the code generated by the app and click 'Verify OTP and continue'."
      ]
    },
    {
      name: 'Dropbox', path: 'Settings > Security > 2FA', description: 'E-commerce, Retail & Streaming', icon: 'https://www.dropbox.com/static/images/favicon.ico', instructions: [
        "Log in to your Dropbox account and go to 'Settings'.",
        "Navigate to the 'Security' tab.",
        "Find 'Two-step verification' and click 'Get started'.",
        "Choose 'Use a mobile app' as your method.",
        "Scan the QR code with the 2Fa Live app to link your account."
      ]
    },
    {
      name: 'Epic Games', path: 'Account > Password & Security', description: 'Digital Games Store & Launcher', icon: 'https://www.epicgames.com/favicon.ico', instructions: [
        "Go to your Epic Games account settings.",
        "Select 'Password & Security' from the left menu.",
        "Scroll down to 'Two-Factor Authentication' and click 'Enable Authenticator App'.",
        "Scan the QR code with the 2Fa Live app and enter the generated code to verify."
      ]
    },
    {
      name: 'Luno', path: 'Profile > Security > 2FA', description: 'Cryptocurrency Trading & Wallet', icon: 'https://www.luno.com/favicon.ico', instructions: [
        "Log in to your Luno account and go to 'Profile'.",
        "Select 'Security' and then 'Two-factor authentication'.",
        "Click on 'Enable Authenticator app'.",
        "Scan the QR code displayed with the 2Fa Live app.",
        "Enter the code from the app into Luno to confirm."
      ]
    },
    {
      name: 'PayPal', path: 'Settings > Security > 2-step verification', description: 'Online Payments & Money Transfer', icon: 'https://www.paypal.com/favicon.ico', instructions: [
        "Log in to PayPal and go to 'Settings' (gear icon).",
        "Select 'Security' from the top menu.",
        "Under '2-step verification', click 'Set up' or 'Update'.",
        "Choose 'Use an authenticator app' and follow the instructions.",
        "Scan the QR code shown with the 2Fa Live app and enter the code into PayPal."
      ]
    },
    {
      name: 'Rockstar Games', path: 'Settings > 2-Step Verification', description: 'Gaming Community & Digital Entertainment', icon: 'https://www.rockstargames.com/favicon.ico', instructions: [
        "Log in to Rockstar Games Social Club.",
        "Go to 'Settings' and then '2-Step Verification'.",
        "Click 'Setup' and follow the prompts.",
        "Scan the QR code provided with the 2Fa Live app.",
        "Enter the verification code from the app to complete the setup."
      ]
    },
    {
      name: 'Snapchat', path: 'Settings > Two-Factor Authentication', description: 'Ephemeral Photo/Video & Messaging', icon: 'https://www.snapchat.com/favicon.ico', instructions: [
        "Open Snapchat, tap your Bitmoji in the top left, then the gear icon for 'Settings'.",
        "Tap 'Two-Factor Authentication' and then 'Authentication App'.",
        "Tap 'Set Up Now' and copy the secret key or scan the QR code.",
        "Use the 2Fa Live app to scan the QR code (or manually enter the key).",
        "Enter the generated code from 2Fa Live into Snapchat to verify."
      ]
    },
    {
      name: 'Binance', path: 'Security > Two-Factor Authentication', description: 'Global Digital Asset Exchange', icon: 'https://www.binance.com/favicon.ico', instructions: [
        "Log in to your Binance account.",
        "Go to 'Security' settings.",
        "Find 'Google Authenticator' (or 'Authenticator App') and click 'Enable'.",
        "Scan the provided QR code with the 2Fa Live app.",
        "Enter the code from the app, along with your login password, to activate 2FA."
      ]
    },
    {
      name: 'G2A', path: 'Security > 2FA', description: 'Digital Key & Gaming Marketplace', icon: 'https://id.g2a.com/favicon.ico', instructions: [
        "Log in to G2A and go to 'My Account'.",
        "Select 'Security' from the left menu.",
        "Under 'Two-Factor Authentication', click 'Enable'.",
        "Scan the QR code with the 2Fa Live app.",
        "Enter the generated code into G2A to finalize the setup."
      ]
    },
    {
      name: 'Jamf', path: 'Account Settings > Security', description: 'Apple Device & Endpoint Management', icon: 'https://www.jamf.com/favicon.ico', instructions: [
        "Log in to your Jamf Cloud instance.",
        "Go to your 'User Profile' or 'Account Settings'.",
        "Look for 'Security' or 'Two-Factor Authentication' settings.",
        "Follow the instructions to enable an authenticator app and display the QR code.",
        "Scan the QR code with the 2Fa Live app and enter the generated code to verify."
      ]
    },
    {
      name: 'Kraken', path: 'Security > 2FA Settings', description: 'Advanced Crypto Trading Platform', icon: 'https://www.kraken.com/favicon.ico', instructions: [
        "Log in to Kraken and navigate to 'Security'.",
        "Select '2FA Settings'.",
        "Choose 'Authenticator App' as your 2FA method.",
        "Scan the QR code shown with the 2Fa Live app.",
        "Enter the code from the app into Kraken to confirm."
      ]
    },
    {
      name: 'Shopify', path: 'Settings > Account > Security', description: 'E-commerce Store & Business Platform', icon: 'https://www.shopify.com/favicon.ico', instructions: [
        "From your Shopify admin, go to 'Settings' > 'Users and permissions'.",
        "Click on your staff account name.",
        "In the 'Two-step authentication' section, click 'Set up'.",
        "Choose 'Authenticator app' as your authentication method.",
        "Scan the QR code with the 2Fa Live app and enter the generated code to verify."
      ]
    },
    {
      name: 'Coinbase', path: 'Settings > Security > 2-step verification', description: 'Cryptocurrency Wallet & Exchange', icon: 'https://www.coinbase.com/favicon.ico', instructions: [
        "Log in to Coinbase and go to 'Profile & Settings'.",
        "Select the 'Security' tab.",
        "Under '2-Step Verification', click 'Enable Authenticator'.",
        "Scan the QR code shown with the 2Fa Live app.",
        "Enter the 6-digit code from the app into Coinbase to complete the setup."
      ]
    },
    {
      name: 'Reddit', path: 'User Settings > Safety & Privacy', description: 'Community Forums & Discussion Hub', icon: 'https://www.reddit.com/favicon.ico', instructions: [
        "Go to Reddit 'User Settings' (profile icon in top right).",
        "Select 'Safety & Privacy' from the left menu.",
        "Scroll down to 'Enable two-factor authentication' and toggle it on.",
        "Choose 'Use an app' and scan the QR code with the 2Fa Live app.",
        "Enter the code from the app into Reddit to confirm."
      ]
    },
    {
      name: 'Twitch', path: 'Settings > Security and Privacy', description: 'Live Video Streaming & Gaming Broadcasts', icon: 'https://www.twitch.tv/favicon.ico', instructions: [
        "Log in to Twitch and go to 'Settings' (profile icon in top right).",
        "Select 'Security and Privacy'.",
        "Under 'Security', find 'Set Up Two-Factor Authentication' and click 'Enable Authenticator'.",
        "Scan the QR code with the 2Fa Live app.",
        "Enter the code from the app into Twitch to verify."
      ]
    },
    {
      name: 'Crypto.com', path: 'Settings > 2FA', description: 'Cryptocurrency Exchange & Financial Services', icon: 'https://crypto.com/favicon.ico', instructions: [
        "Open the Crypto.com App.",
        "Go to 'Settings' (gear icon) > 'Security' > '2-Factor Authentication'.",
        "Tap 'Enable 2FA' or 'Authenticator App'.",
        "Scan the QR code with the 2Fa Live app.",
        "Enter the generated code into the Crypto.com app to complete the activation."
      ]
    },
    {
      name: 'Other / Custom', path: 'Security > 2FA / MFA Settings', description: 'For any online account not listed', icon: '', instructions: [
        "Log into your account.",
        "Navigate to your Security or Privacy settings.",
        "Find 'Two-Factor Authentication' or '2-Step Verification'.",
        "Choose 'Authenticator App' as your method.",
        "Scan the QR code using the 2Fa Live app.",
        "Enter the 6-digit code to confirm and save recovery codes."
      ]
    },
  ];

  // Drag handlers
  const handleMouseDown = (e) => {
    if (dragByHeaderOnly && !e.target.closest('.drag-handle')) return;
    setDragging(true);
    const rect = dragRef.current.getBoundingClientRect();
    offsetRef.current = {
      x: e.clientX - rect.left,
      y: e.clientY - rect.top
    };
  };

  const handleMouseMove = (e) => {
    if (!dragging) return;
    setPosition({
      x: e.clientX - offsetRef.current.x,
      y: e.clientY - offsetRef.current.y
    });
  };

  const handleMouseUp = () => setDragging(false);

  // Close card when clicking outside
  const handleClickOutside = (e) => {
    if (dragRef.current && !dragRef.current.contains(e.target)) {
      setSelectedPlatform(null);
    }
  };

  useEffect(() => {
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  return (
    <div
      className="space-y-10 pb-16 relative"
      onMouseMove={handleMouseMove}
      onMouseUp={handleMouseUp}
    >

      <Helmet>
        {/* Meta Title */}
        <title>How to Enable 2FA on Google, Facebook, Instagram & More | 2Fa Live</title>

        {/* Meta Description */}
        <meta
          name="description"
          content="Enable Two-Factor Authentication on popular platforms like Google, Facebook, Insta, and more. Keep your accounts secure with 2Fa Live."/>
        <link rel="canonical" href="http://localhost:3000/how-to-enable"/>
        <meta name="robots" content="index, follow"/>
        <meta name="keywords" content="2FA, two-factor authentication, Google 2FA, Facebook 2FA, Instagram 2FA, GitHub 2FA, enable 2FA, authentication app, security, account protection"/>
      </Helmet>
      <h1 className="text-4xl font-bold">How to Enable</h1>

      {/* Platform grid */}
      <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm max-w-3xl mx-auto">
        <div className='flex my-5'>
          <h3 className="text-xl font-bold flex items-center gap-2">Select Your Platform</h3>
          <div className="ml-auto flex bg-white-800 rounded-xl p-1">
            <button
              onClick={() => setView(view === "grid" ? "list" : "grid")}
              className="p-2 rounded-lg bg-slate-700 text-white"
            >
              {view === "grid" ? <List className="w-5 h-5"/> : <LayoutGrid className="w-5 h-5"/>}
            </button>
          </div>
        </div>

        <div className={
          view === "grid"
            ? "grid grid-cols-[repeat(auto-fill,minmax(220px,1fr))] gap-5"
            : "flex flex-col gap-4"
        }>
          {platforms.map(platform => (
            <button
              key={platform.name}
              onClick={() => {
                setSelectedPlatform(platform);
                setPosition({ x: window.innerWidth / 2 - cardWidth / 2, y: 100 });
              }}
              className="h-full p-3 bg-slate-50 rounded-2xl border border-slate-200 hover:border-emerald-500 hover:shadow-xl hover:-translate-y-1 transition-all duration-300 text-left group relative"
            >
              <div className="flex items-center gap-4 h-full">
                {platform.icon ? (
                  <img src={platform.icon} alt="" className="w-10 h-10 rounded-md" referrerPolicy="no-referrer"/>
                ) : <Shield className="w-10 h-10 text-emerald-500"/>}

                <div className="flex-1">
                  <p className="text-lg font-semibold text-slate-800 flex items-center gap-2">
                    {platform.name}
                    <ExternalLink className="w-4 h-4 opacity-0 group-hover:opacity-100 transition-opacity text-emerald-500"/>
                  </p>
                  <p className="text-sm text-slate-500 mt-1">{platform.description}</p>
                </div>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Floating Card with overlay */}
      {selectedPlatform && (
        <>
          {/* Backdrop */}
          <div className="fixed inset-0 bg-black/20 backdrop-blur-sm z-40"></div>

          {/* Draggable card */}
          <div
            ref={dragRef}
            onMouseDown={handleMouseDown}
            className={`fixed ${cardBg} ${cardBlur} ${cardShadow} ${cardBorder} rounded-3xl p-6 z-50 transition-all duration-300 cursor-${dragByHeaderOnly ? 'default' : 'move'} animate-fadeIn`}
            style={{ top: position.y, left: position.x, width: cardWidth, height: cardHeight }}
          >
            {/* Header */}
            <div className={`drag-handle ${dragByHeaderOnly ? 'cursor-move' : ''}`}>
              <div className="flex justify-between items-center mb-4">
                <div>
                  <h2 className="text-2xl font-bold">{selectedPlatform.name}</h2>
                  <p className="text-sm text-slate-500">{selectedPlatform.description}</p>
                </div>
                <button
                  className="p-2 rounded-full hover:bg-slate-200 cursor-pointer"
                  onClick={() => setSelectedPlatform(null)}
                >
                  <X className="w-5 h-5"/>
                </button>
              </div>
            </div>

            {/* Instructions */}
            <ol className="list-decimal list-inside space-y-2">
              {selectedPlatform.instructions.map((step, index) => (
                <li key={index}>{step}</li>
              ))}
            </ol>
          </div>
        </>
      )}
    </div>
  );
}
// import React from 'react';
// import { Shield, LayoutGrid, List, CheckCircle2, Info, ExternalLink } from 'lucide-react';
// import { motion } from 'motion/react';
// import { useNavigate } from 'react-router-dom';
// import { useState } from 'react';

// export default function HowToEnable() {
//   const navigate = useNavigate();
//   const [view, setView] = useState("grid");

//   const platforms = [
//     {
//       name: 'Google', path: 'Security > 2-Step Verification', description: 'Email, Cloud Storage & Productivity', icon: 'https://www.google.com/favicon.ico', instructions: [
//         "Go to your Google Account by clicking your profile picture and selecting 'Manage your Google Account'.",
//         "Select the 'Security' tab from the left-hand menu.",
//         "Under 'Signing in to Google', click on '2-Step Verification' and then 'Get Started'.",
//         "Follow the on-screen prompts.",
//         "When asked to choose a verification method, select 'Authenticator app'.",
//         "Scan the QR code using the 2Fa Live app to complete setup."
//       ]
//     },
//     {
//       name: 'Facebook', path: 'Settings > Password & Security', description: 'Social Networking Platform', icon: 'https://www.facebook.com/favicon.ico', instructions: [
//         "Click the down-arrow in the top-right corner.",
//         "Go to 'Settings & Privacy' > 'Settings'.",
//         "Click on 'Security and Login'.",
//         "Scroll to 'Use two-factor authentication' and click 'Edit'.",
//         "Select 'Authentication App' as your method.",
//         "Scan the QR code with the 2Fa Live app to finalize setup."
//       ]
//     },
//     {
//       name: 'Instagram', path: 'Settings > Security > 2FA', description: 'Social Networking Platform', icon: 'https://www.instagram.com/static/images/ico/favicon.ico/36b304827392.ico', instructions: [
//         "Go to your profile and tap the menu icon (three horizontal lines) in the top-right corner.",
//         "Tap 'Settings' > 'Security' > 'Two-Factor Authentication'.",
//         "Tap 'Get Started'. Choose 'Authentication App' as your method.",
//         "Follow the on-screen instructions. Instagram will show you a QR code.",
//         "Scan the QR code with the 2Fa Live app to link your account."
//       ]
//     },
//     {
//       name: 'X (Social Platform)', path: 'Settings > Security > 2FA', description: 'Visual Sharing & Social Media', icon: 'https://abs.twimg.com/favicons/twitter.ico', instructions: [
//         "Log into your account.",
//         "Navigate to your Security or Privacy settings.",
//         "Find 'Two-Factor Authentication' or '2-Step Verification'.",
//         "Choose 'Authenticator App' as your method.",
//         "Scan the QR code using the 2Fa Live app.",
//         "Enter the 6-digit code to confirm and save recovery codes."
//       ]
//     },
//     {
//       name: 'GitHub', path: 'Settings > Password & Security', description: 'Microblogging & News Updates', icon: 'https://github.com/favicon.ico', instructions: [
//         "In the upper-right corner of any page, click your profile photo, then click 'Settings'.",
//         "In the 'Access' section of the sidebar, click 'Password and authentication'.",
//         "In the 'Two-factor authentication' section, click 'Enable two-factor authentication'.",
//         "Under 'Scan the QR code', use the 2Fa Live app to scan the code.",
//         "Enter the code generated by the app to complete the setup."
//       ]
//     },
//     {
//       name: 'Amazon', path: 'Login & Security > 2SV', description: 'Code Collaboration & Version Control', icon: 'https://www.amazon.com/favicon.ico', instructions: [
//         "Go to 'Your Account' > 'Login & Security'.",
//         "Click 'Edit' next to 'Two-Step Verification (2SV) Settings'.",
//         "Click 'Get Started'. Choose 'Authenticator App' as your method.",
//         "The site will display a QR code. Use the 2Fa Live app to scan it.",
//         "Enter the code generated by the app and click 'Verify OTP and continue'."
//       ]
//     },
//     {
//       name: 'Dropbox', path: 'Settings > Security > 2FA', description: 'E-commerce, Retail & Streaming', icon: 'https://www.dropbox.com/static/images/favicon.ico', instructions: [
//         "Log in to your Dropbox account and go to 'Settings'.",
//         "Navigate to the 'Security' tab.",
//         "Find 'Two-step verification' and click 'Get started'.",
//         "Choose 'Use a mobile app' as your method.",
//         "Scan the QR code with the 2Fa Live app to link your account."
//       ]
//     },
//     {
//       name: 'Epic Games', path: 'Account > Password & Security', description: 'Digital Games Store & Launcher', icon: 'https://www.epicgames.com/favicon.ico', instructions: [
//         "Go to your Epic Games account settings.",
//         "Select 'Password & Security' from the left menu.",
//         "Scroll down to 'Two-Factor Authentication' and click 'Enable Authenticator App'.",
//         "Scan the QR code with the 2Fa Live app and enter the generated code to verify."
//       ]
//     },
//     {
//       name: 'Luno', path: 'Profile > Security > 2FA', description: 'Cryptocurrency Trading & Wallet', icon: 'https://www.luno.com/favicon.ico', instructions: [
//         "Log in to your Luno account and go to 'Profile'.",
//         "Select 'Security' and then 'Two-factor authentication'.",
//         "Click on 'Enable Authenticator app'.",
//         "Scan the QR code displayed with the 2Fa Live app.",
//         "Enter the code from the app into Luno to confirm."
//       ]
//     },
//     {
//       name: 'PayPal', path: 'Settings > Security > 2-step verification', description: 'Online Payments & Money Transfer', icon: 'https://www.paypal.com/favicon.ico', instructions: [
//         "Log in to PayPal and go to 'Settings' (gear icon).",
//         "Select 'Security' from the top menu.",
//         "Under '2-step verification', click 'Set up' or 'Update'.",
//         "Choose 'Use an authenticator app' and follow the instructions.",
//         "Scan the QR code shown with the 2Fa Live app and enter the code into PayPal."
//       ]
//     },
//     {
//       name: 'Rockstar Games', path: 'Settings > 2-Step Verification', description: 'Gaming Community & Digital Entertainment', icon: 'https://www.rockstargames.com/favicon.ico', instructions: [
//         "Log in to Rockstar Games Social Club.",
//         "Go to 'Settings' and then '2-Step Verification'.",
//         "Click 'Setup' and follow the prompts.",
//         "Scan the QR code provided with the 2Fa Live app.",
//         "Enter the verification code from the app to complete the setup."
//       ]
//     },
//     {
//       name: 'Snapchat', path: 'Settings > Two-Factor Authentication', description: 'Ephemeral Photo/Video & Messaging', icon: 'https://www.snapchat.com/favicon.ico', instructions: [
//         "Open Snapchat, tap your Bitmoji in the top left, then the gear icon for 'Settings'.",
//         "Tap 'Two-Factor Authentication' and then 'Authentication App'.",
//         "Tap 'Set Up Now' and copy the secret key or scan the QR code.",
//         "Use the 2Fa Live app to scan the QR code (or manually enter the key).",
//         "Enter the generated code from 2Fa Live into Snapchat to verify."
//       ]
//     },
//     {
//       name: 'Binance', path: 'Security > Two-Factor Authentication', description: 'Global Digital Asset Exchange', icon: 'https://www.binance.com/favicon.ico', instructions: [
//         "Log in to your Binance account.",
//         "Go to 'Security' settings.",
//         "Find 'Google Authenticator' (or 'Authenticator App') and click 'Enable'.",
//         "Scan the provided QR code with the 2Fa Live app.",
//         "Enter the code from the app, along with your login password, to activate 2FA."
//       ]
//     },
//     {
//       name: 'G2A', path: 'Security > 2FA', description: 'Digital Key & Gaming Marketplace', icon: 'https://id.g2a.com/favicon.ico', instructions: [
//         "Log in to G2A and go to 'My Account'.",
//         "Select 'Security' from the left menu.",
//         "Under 'Two-Factor Authentication', click 'Enable'.",
//         "Scan the QR code with the 2Fa Live app.",
//         "Enter the generated code into G2A to finalize the setup."
//       ]
//     },
//     {
//       name: 'Jamf', path: 'Account Settings > Security', description: 'Apple Device & Endpoint Management', icon: 'https://www.jamf.com/favicon.ico', instructions: [
//         "Log in to your Jamf Cloud instance.",
//         "Go to your 'User Profile' or 'Account Settings'.",
//         "Look for 'Security' or 'Two-Factor Authentication' settings.",
//         "Follow the instructions to enable an authenticator app and display the QR code.",
//         "Scan the QR code with the 2Fa Live app and enter the generated code to verify."
//       ]
//     },
//     {
//       name: 'Kraken', path: 'Security > 2FA Settings', description: 'Advanced Crypto Trading Platform', icon: 'https://www.kraken.com/favicon.ico', instructions: [
//         "Log in to Kraken and navigate to 'Security'.",
//         "Select '2FA Settings'.",
//         "Choose 'Authenticator App' as your 2FA method.",
//         "Scan the QR code shown with the 2Fa Live app.",
//         "Enter the code from the app into Kraken to confirm."
//       ]
//     },
//     {
//       name: 'Shopify', path: 'Settings > Account > Security', description: 'E-commerce Store & Business Platform', icon: 'https://www.shopify.com/favicon.ico', instructions: [
//         "From your Shopify admin, go to 'Settings' > 'Users and permissions'.",
//         "Click on your staff account name.",
//         "In the 'Two-step authentication' section, click 'Set up'.",
//         "Choose 'Authenticator app' as your authentication method.",
//         "Scan the QR code with the 2Fa Live app and enter the generated code to verify."
//       ]
//     },
//     {
//       name: 'Coinbase', path: 'Settings > Security > 2-step verification', description: 'Cryptocurrency Wallet & Exchange', icon: 'https://www.coinbase.com/favicon.ico', instructions: [
//         "Log in to Coinbase and go to 'Profile & Settings'.",
//         "Select the 'Security' tab.",
//         "Under '2-Step Verification', click 'Enable Authenticator'.",
//         "Scan the QR code shown with the 2Fa Live app.",
//         "Enter the 6-digit code from the app into Coinbase to complete the setup."
//       ]
//     },
//     {
//       name: 'Reddit', path: 'User Settings > Safety & Privacy', description: 'Community Forums & Discussion Hub', icon: 'https://www.reddit.com/favicon.ico', instructions: [
//         "Go to Reddit 'User Settings' (profile icon in top right).",
//         "Select 'Safety & Privacy' from the left menu.",
//         "Scroll down to 'Enable two-factor authentication' and toggle it on.",
//         "Choose 'Use an app' and scan the QR code with the 2Fa Live app.",
//         "Enter the code from the app into Reddit to confirm."
//       ]
//     },
//     {
//       name: 'Twitch', path: 'Settings > Security and Privacy', description: 'Live Video Streaming & Gaming Broadcasts', icon: 'https://www.twitch.tv/favicon.ico', instructions: [
//         "Log in to Twitch and go to 'Settings' (profile icon in top right).",
//         "Select 'Security and Privacy'.",
//         "Under 'Security', find 'Set Up Two-Factor Authentication' and click 'Enable Authenticator'.",
//         "Scan the QR code with the 2Fa Live app.",
//         "Enter the code from the app into Twitch to verify."
//       ]
//     },
//     {
//       name: 'Crypto.com', path: 'Settings > 2FA', description: 'Cryptocurrency Exchange & Financial Services', icon: 'https://crypto.com/favicon.ico', instructions: [
//         "Open the Crypto.com App.",
//         "Go to 'Settings' (gear icon) > 'Security' > '2-Factor Authentication'.",
//         "Tap 'Enable 2FA' or 'Authenticator App'.",
//         "Scan the QR code with the 2Fa Live app.",
//         "Enter the generated code into the Crypto.com app to complete the activation."
//       ]
//     },
//     {
//       name: 'Other / Custom', path: 'Security > 2FA / MFA Settings', description: 'For any online account not listed', icon: '', instructions: [
//         "Log into your account.",
//         "Navigate to your Security or Privacy settings.",
//         "Find 'Two-Factor Authentication' or '2-Step Verification'.",
//         "Choose 'Authenticator App' as your method.",
//         "Scan the QR code using the 2Fa Live app.",
//         "Enter the 6-digit code to confirm and save recovery codes."
//       ]
//     },
//   ];

//   const handlePlatformClick = (platform) => {
//     // Navigate to a new page with the platform data
//     navigate('/platform-instructions', { state: { platform } });
//   };

//   return (
//     <div className="space-y-10 pb-16">
      
//       <h1 className="text-4xl font-bold">How to Enable</h1>

//       {/* PLATFORM GRID */}
//       <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm max-w-3xl mx-auto">
//         <div className='flex my-5'>
//           <h3 className="text-xl font-bold flex items-center gap-2">Select Your Platform</h3>
//           <div className="ml-auto flex bg-white-800 rounded-xl p-1">
//             <button onClick={() => setView(view === "grid" ? "list" : "grid")} className="p-2 rounded-lg bg-slate-700 text-white">
//               {view === "grid" ? (
//                 <List className="w-5 h-5"/>
//               ) : (
//                 <LayoutGrid className="w-5 h-5"/>
//               )}
//             </button>
//           </div>
//         </div>
        
//         <div className={
//           view === "grid"
//             ? "grid grid-cols-[repeat(auto-fill,minmax(220px,1fr))] gap-5"
//             : "flex flex-col gap-4"
//         }>
//           {platforms.map((platform) => (
//             <button
//               key={platform.name}
//               onClick={() => handlePlatformClick(platform)}
//               className="h-full p-3 bg-slate-50 rounded-2xl border border-slate-200 hover:border-emerald-500 hover:shadow-xl hover:-translate-y-1 transition-all duration-300 text-left group">
//               <div className="flex items-center gap-4 h-full">
//                 {platform.icon ? (
//                   <img src={platform.icon} alt="" className="w-10 h-10 rounded-md" referrerPolicy="no-referrer"/>
//                 ) : ( <Shield className="w-10 h-10 text-emerald-500"/>)}

//                 <div className="flex-1">
//                   <p className="text-lg font-semibold text-slate-800 flex items-center gap-2">
//                     {platform.name}
//                     <ExternalLink className="w-4 h-4 opacity-0 group-hover:opacity-100 transition-opacity text-emerald-500"/>
//                   </p>
//                   <p className="text-sm text-slate-500 mt-1">
//                     {platform.description}
//                   </p> 
//                 </div>
//               </div>
//             </button>
//           ))}
//         </div>
//       </div>
//     </div>
//   );
// }